2017-11-14 15:15:10,195 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/cygdrive/c/Program Files/nodejs:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Users/Aseem/AppData/Roaming/npm:/cygdrive/c/Program Files/eclipse)
'
2017-11-28 13:14:30,593 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/d/CV/project/College Library Record Application)
'
2017-11-29 16:29:41,503 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-11-29 18:49:52,353 [Worker-7] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-11-29 20:31:22,609 [Worker-9] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-12 23:51:54,621 [Worker-4] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-13 14:31:10,835 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-13 23:55:47,892 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-18 22:52:26,976 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-19 11:50:12,355 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-19 14:09:09,854 [Worker-0] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-21 00:16:28,277 [Worker-4] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-21 12:34:51,983 [Worker-8] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
2017-12-24 15:51:25,666 [Worker-9] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/d/Course/LICT/Java/first/first)
'
2017-12-27 07:16:00,235 [Worker-7] WARN  org.eclipse.jgit.util.FS_Win32 - Exception caught during execution of command '[bash, --login, -c, which git]' in 'C:\Users\Aseem', return code '1', error message 'which: no git in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin/client:/cygdrive/c/Program Files/Java/jre1.8.0_131/bin:/cygdrive/c/Program Files/Java/jre1.8.0_131/lib/i386:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/bin:/usr/bin:/usr/bin:/cygdrive/c/Program Files/Java/jdk1.8.0_131/bin:/cygdrive/c/Program Files/apache-maven-3.5.0-bin/apache-maven-3.5.0/bin:/cygdrive/c/Program Files/eclipse)
'
